---
variables:
  BRANCH: $CI_COMMIT_REF_NAME
  PIPELINE_ID: beacon-$CI_PIPELINE_ID

stages:
    - test
    - cleanup

test:
    stage: test
    script:
        - make test

cleanup:
  stage: cleanup
  script:
    - docker ps -aq --filter "name=${PIPELINE_ID}-*" | xargs -r docker rm  -f -v
    - docker images --quiet --filter "reference=local/${PIPELINE_ID}*" | xargs -r docker rmi
  when: always
